### PR TITLE
add basic enum type converter

### PR DESCRIPTION
**Pull request by TimWhiting**
Still haven't made sure not to override user's custom type converters, but does this look like the right direction @schultek?

### CODE REVIEW

**Comment by schultek** [comment]
Direction is good. I think we could define a general `EnumTypeConverter` or `EnumConverter` that is then just used for each enum, without the need to create custom classes for each enum. Something like:

```dart
// somewhere inside stormberry package

class EnumTypeConverter<T extends Enum> extends TypeConverter<T> {

  const EnumTypeConverter(this.values);
  final List<T> values;

  @override
  String encode(T value) => value.name;

  @override
  T decode(dynamic value) => values.byName(value as String);
}

// inside the generated code

final registry = ModelRegistry({
  typeOf<EnumValue>():  EnumTypeConverter<EnumValue>(EnumValue.values),
  ...
});
```

**Comment by TimWhiting** [comment]
Done, also tested to make sure enum serializers defined by users override those defined by us. (In maps / map literals the last entry with a key overwrites previous entries with the same key, so I just put enum serializers before all other serializers).

**Comment by schultek** [comment]
It should be doable to check the enums agains the custom type converters in the builder right? I think it would be much cleaner to remove those duplicates if its not too much work.

Thanks anyways.

**Comment by TimWhiting** [comment]
Done

**Pull request merged**
